import { mkdir, readdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { BflClient } from "./bfl-client.js";
import { ClaudeFormatter } from "./claude-formatter.js";
import { OpenAiImageClient } from "./openai-image-client.js";
import { loadPack } from "./parse-pack.js";
import { buildRawPngMetadata, embedPngMetadata } from "./png-metadata.js";
import {
  getImageProvider,
  MAX_CONCURRENCY,
  parseBoundedIntegerFlag,
  resolveSafeOutputPath,
} from "./validation.js";
import type {
  AssetSpec,
  FormattedImagePrompt,
  GenerationRecord,
} from "./types.js";

export interface GenerateOptions {
  /** Absolute path to pack.toml or a directory containing it. */
  packPath: string;
  /**
   * Container directory for all outputs. Raw Flux PNGs go to `<outDir>/raw/`;
   * post-processed assets go to `<outDir>/processed/` when --and-process is on.
   *
   * When omitted, defaults to `<packDir>/output/` — co-located with the pack.
   */
  outDir?: string;
  /** Filter to this section name (case-insensitive substring match). */
  section?: string;
  /**
   * Filter to one or more asset ids (case-insensitive exact match against
   * AssetSpec.id). Comma-separated string or string array. When combined
   * with `section`, the intersection is used. Skips `limit`'s round-robin
   * when asset ids are explicit.
   */
  asset?: string | readonly string[];
  /** Limit to at most N assets (smoke test). Picks one-per-section when possible. */
  limit?: number;
  /** Regenerate selected assets even when their raw output PNG already exists. */
  reprocess?: boolean;
  /** Skip API calls — print what would happen. */
  dryRun?: boolean;
  /** Only print formatted Claude outputs; no image API calls, no disk writes. */
  previewOnly?: boolean;
  /** Override the model from the pack settings. */
  modelOverride?: string;
  /** Number of assets to process in parallel. */
  concurrency?: number;
  /**
   * After generation completes, run the Python post-processor on assets
   * generated by this command with output going to processed/. The separate
   * `process` subcommand remains available for re-processing without
   * regenerating.
   */
  andProcess?: boolean;
  /** Anthropic API key. */
  anthropicApiKey: string;
  /** BFL API key. */
  bflApiKey: string;
  /** OpenAI API key. */
  openaiApiKey: string;
  /** Progress callback — invoked after each asset completes or fails. */
  onProgress?: (event: ProgressEvent) => void;
}

export type ProgressEvent =
  | { kind: "start"; total: number }
  | { kind: "formatting"; spec: AssetSpec; index: number; total: number }
  | { kind: "generating"; spec: AssetSpec; index: number; total: number }
  | {
      kind: "done";
      spec: AssetSpec;
      index: number;
      total: number;
      record: GenerationRecord;
    }
  | {
      kind: "error";
      spec: AssetSpec;
      index: number;
      total: number;
      error: string;
    }
  | {
      kind: "complete";
      successes: number;
      failures: number;
      total_cost_usd: number;
      duration_ms: number;
    };

export interface GenerateSummary {
  successes: GenerationRecord[];
  failures: Array<{ spec: AssetSpec; error: string }>;
  total_cost_usd: number;
  duration_ms: number;
  /** Absolute path to the raw output directory actually used. */
  rawDir: string;
  /** Absolute path to the processed output directory (only populated when
   *  --and-process is set and at least one generation succeeded). */
  processedDir?: string;
  /** Post-process outcome — only set when --and-process ran. */
  postProcess?: {
    exit_code: number;
    duration_ms: number;
  };
  /** Selected pack assets skipped because their raw PNG already exists. */
  skippedExisting: number;
}

export async function generate(
  opts: GenerateOptions,
): Promise<GenerateSummary> {
  const doc = await loadPack(opts.packPath);
  const model = opts.modelOverride ?? doc.settings.model;

  // Output is anchored to the pack directory by default so generated assets
  // sit next to the source that produced them. --out still overrides for
  // one-off runs or CI artifacts.
  const outRoot = opts.outDir ?? resolve(doc.packDir, "output");
  const rawDir = resolve(outRoot, "raw");
  const processedDir = resolve(outRoot, "processed");

  const { specs: filtered, skippedExisting } = await filterSpecs(
    doc.specs,
    opts.section,
    opts.asset,
    opts.limit,
    {
      rawDir,
      reprocess: opts.reprocess === true,
    },
  );
  const concurrency = parseBoundedIntegerFlag(
    String(opts.concurrency ?? 1),
    "concurrency",
    { min: 1, max: MAX_CONCURRENCY },
  );
  validateCredentialsForSelectedRun({
    selectedCount: filtered.length,
    dryRun: opts.dryRun === true,
    previewOnly: opts.previewOnly === true,
    model,
    anthropicApiKey: opts.anthropicApiKey,
    bflApiKey: opts.bflApiKey,
    openaiApiKey: opts.openaiApiKey,
  });

  opts.onProgress?.({ kind: "start", total: filtered.length });

  const successes: GenerationRecord[] = [];
  const failures: Array<{ spec: AssetSpec; error: string }> = [];
  const previewOutputs = new Array<string | undefined>(filtered.length);
  const batchStart = Date.now();

  // Claude formatter instances are cached per model/style/palette pair so
  // prompt caching can still kick in when assets share resolved context.
  const formatterCache = new Map<string, ClaudeFormatter>();
  const imageClient =
    filtered.length === 0 || opts.dryRun || opts.previewOnly
      ? undefined
      : createImageClient({
          model,
          bflApiKey: opts.bflApiKey,
          openaiApiKey: opts.openaiApiKey,
        });

  let nextIndex = 0;
  const processOne = async (spec: AssetSpec, index: number): Promise<void> => {
    try {
      if (opts.dryRun) {
        // No API calls at all — just confirm the pack parses and is valid.
        const record = buildRecord({
          spec,
          packTitle: doc.settings.title,
          preset: doc.settings.preset,
          fmt: {
            prompt: "(dry-run)",
            cost_usd: 0,
          },
          model,
          taskId: "(dry-run)",
          imageCostUsd: 0,
          durationMs: 0,
        });
        successes.push(record);
        opts.onProgress?.({
          kind: "done",
          spec,
          index,
          total: filtered.length,
          record,
        });
        return;
      }

      opts.onProgress?.({
        kind: "formatting",
        spec,
        index,
        total: filtered.length,
      });

      const formatter = getFormatterForSpec(
        spec,
        doc.styles,
        doc.palettes,
        formatterCache,
        opts.anthropicApiKey,
        model,
      );
      // Identity (if set) is spliced into the user message. Skipping it
      // when null means packs without cultural grounding pay no tokens for
      // a feature they don't use.
      const identity = spec.identity_id
        ? doc.identities[spec.identity_id]
        : undefined;
      const fmt = await formatter.format(spec.description, {
        assetTypeHint: spec.type,
        aspectHint: spec.aspect,
        fileHint: spec.file,
        promptFragment: spec.prompt_fragment,
        identity,
      });

      if (opts.previewOnly) {
        previewOutputs[index] = buildPreviewOutput(spec, fmt.prompt);
        return;
      }

      opts.onProgress?.({
        kind: "generating",
        spec,
        index,
        total: filtered.length,
      });

      if (!imageClient) {
        throw new Error("Image client was not initialized.");
      }
      const imageResult = await imageClient.generate({
        prompt: fmt.prompt,
        size: spec.size,
        aspect: spec.aspect,
      });

      // Write the PNG to disk at its target path inside the raw output dir.
      const pngPath = resolveSafeOutputPath(
        rawDir,
        spec.file,
        `asset "${spec.id}" output path`,
      );
      await mkdir(dirname(pngPath), { recursive: true });

      const record = buildRecord({
        spec,
        packTitle: doc.settings.title,
        preset: doc.settings.preset,
        fmt,
        model,
        taskId: imageResult.task_id,
        imageCostUsd: imageResult.cost_usd,
        durationMs: imageResult.duration_ms,
      });
      const pngWithMetadata = embedPngMetadata(
        imageResult.image,
        buildRawPngMetadata(record),
      );
      await writeFile(pngPath, pngWithMetadata);

      // Sidecar JSON — complete reproducibility record next to each PNG.
      const jsonPath = `${pngPath.slice(0, -4)}.json`;
      await writeFile(jsonPath, JSON.stringify(record, null, 2));

      successes.push(record);
      opts.onProgress?.({
        kind: "done",
        spec,
        index,
        total: filtered.length,
        record,
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      failures.push({ spec, error: msg });
      opts.onProgress?.({
        kind: "error",
        spec,
        index,
        total: filtered.length,
        error: msg,
      });
    }
  };

  const worker = async (): Promise<void> => {
    while (true) {
      const index = nextIndex;
      nextIndex++;
      if (index >= filtered.length) return;
      await processOne(filtered[index], index);
    }
  };

  await Promise.all(
    Array.from(
      { length: Math.min(concurrency, Math.max(filtered.length, 1)) },
      () => worker(),
    ),
  );

  if (opts.previewOnly) {
    for (const preview of previewOutputs) {
      if (preview) console.log(preview);
    }
  }

  const total_cost_usd = successes.reduce(
    (sum, r) => sum + r.cost_usd + r.claude_cost_usd,
    0,
  );

  const duration_ms = Date.now() - batchStart;

  opts.onProgress?.({
    kind: "complete",
    successes: successes.length,
    failures: failures.length,
    total_cost_usd,
    duration_ms,
  });

  // Post-processing runs only the assets generated by this command. That keeps
  // targeted generation from sweeping the whole raw directory and overwriting
  // unrelated processed outputs.
  let postProcess: GenerateSummary["postProcess"] | undefined;
  if (
    opts.andProcess &&
    !opts.dryRun &&
    !opts.previewOnly &&
    successes.length > 0
  ) {
    const selectedAllPackAssets =
      successes.length === doc.specs.length &&
      skippedExisting === 0 &&
      !opts.section &&
      !opts.asset &&
      !opts.limit;
    postProcess = await runPostProcessor({
      rawDir,
      processedDir,
      concurrency,
      assetIds: selectedAllPackAssets
        ? undefined
        : successes.map((record) => record.spec_id),
      reprocess: opts.reprocess === true,
      skipAtlases: !selectedAllPackAssets,
    });
  }

  return {
    successes,
    failures,
    total_cost_usd,
    duration_ms,
    rawDir,
    // Only surface processedDir when we actually ran the post-processor —
    // otherwise the summary would promise an output that doesn't exist.
    processedDir: postProcess ? processedDir : undefined,
    postProcess,
    skippedExisting,
  };
}

async function runPostProcessor(args: {
  rawDir: string;
  processedDir: string;
  concurrency: number;
  assetIds: readonly string[] | undefined;
  reprocess: boolean;
  skipAtlases: boolean;
}): Promise<{ exit_code: number; duration_ms: number }> {
  // Locate post/process.py relative to this compiled module. `import.meta.url`
  // points at dist/generate.js in production, so ../post/process.py resolves
  // to the repo's post directory.
  const here = fileURLToPath(import.meta.url);
  const scriptPath = resolve(dirname(here), "..", "post", "process.py");
  const processArgs = [
    scriptPath,
    args.rawDir,
    args.processedDir,
    "--concurrency",
    String(args.concurrency),
  ];
  if (args.assetIds && args.assetIds.length > 0) {
    processArgs.push("--asset", args.assetIds.join(","));
  }
  if (args.reprocess) {
    processArgs.push("--reprocess");
  }
  if (args.skipAtlases) {
    processArgs.push("--skip-atlases");
  }

  const started = Date.now();
  const exitCode: number = await new Promise((resolveFn, rejectFn) => {
    const child = spawn(
      "python3",
      processArgs,
      { stdio: "inherit" },
    );
    child.on("close", (code) => resolveFn(code ?? 0));
    child.on("error", rejectFn);
  });
  return { exit_code: exitCode, duration_ms: Date.now() - started };
}

async function filterSpecs(
  specs: AssetSpec[],
  section: string | undefined,
  asset: string | readonly string[] | undefined,
  limit: number | undefined,
  existingFilter: { rawDir: string; reprocess: boolean },
): Promise<{ specs: AssetSpec[]; skippedExisting: number }> {
  let filtered = specs;
  if (section) {
    const needle = section.toLowerCase();
    filtered = filtered.filter((s) =>
      s.section.toLowerCase().includes(needle) ||
      s.section_id.toLowerCase().includes(needle),
    );
  }

  let hasAssetFilter = false;
  if (asset) {
    hasAssetFilter = true;
    const ids = new Set(
      (Array.isArray(asset) ? asset : String(asset).split(","))
        .map((s) => s.trim().toLowerCase())
        .filter((s) => s.length > 0),
    );
    filtered = filtered.filter((s) => ids.has(s.id.toLowerCase()));
  }

  let skippedExisting = 0;
  if (!existingFilter.reprocess) {
    const existing = await listRawOutputFiles(existingFilter.rawDir);
    const before = filtered.length;
    filtered = filtered.filter((s) => {
      const jsonFile = `${s.file.slice(0, -4)}.json`;
      return !existing.has(s.file) && !existing.has(jsonFile);
    });
    skippedExisting = before - filtered.length;
  }

  if (
    !hasAssetFilter &&
    limit !== undefined &&
    limit > 0 &&
    limit < filtered.length
  ) {
    // Pick one per section where possible, then fill up.
    filtered = pickSampleAcrossSections(filtered, limit);
  }
  return { specs: filtered, skippedExisting };
}

async function listRawOutputFiles(rawDir: string): Promise<Set<string>> {
  const files = new Set<string>();

  const walk = async (dir: string, prefix: string): Promise<void> => {
    const entries = await readdir(dir, { withFileTypes: true }).catch((err) => {
      if (isNodeError(err) && err.code === "ENOENT") return [];
      throw err;
    });

    for (const entry of entries) {
      const relativePath = prefix ? `${prefix}/${entry.name}` : entry.name;
      const absolutePath = join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(absolutePath, relativePath);
      } else if (entry.isFile()) {
        files.add(relativePath);
      }
    }
  };

  await walk(rawDir, "");
  return files;
}

function isNodeError(err: unknown): err is NodeJS.ErrnoException {
  return err instanceof Error && "code" in err;
}

function validateCredentialsForSelectedRun(args: {
  selectedCount: number;
  dryRun: boolean;
  previewOnly: boolean;
  model: string;
  anthropicApiKey: string;
  bflApiKey: string;
  openaiApiKey: string;
}): void {
  if (args.selectedCount === 0 || args.dryRun) return;

  if (!args.anthropicApiKey) {
    throw new Error(
      "error: ANTHROPIC_API_KEY is not set. Claude formatting is required.",
    );
  }
  if (args.previewOnly) return;

  const provider = getImageProvider(args.model);
  if (provider === "bfl" && !args.bflApiKey) {
    throw new Error(
      "error: BFL_API_KEY is not set. Export it or use --dry-run / --preview.",
    );
  }
  if (provider === "openai" && !args.openaiApiKey) {
    throw new Error(
      "error: OPENAI_API_KEY is not set. Export it or use --dry-run / --preview.",
    );
  }
}

function pickSampleAcrossSections(
  specs: AssetSpec[],
  limit: number,
): AssetSpec[] {
  const bySection = new Map<string, AssetSpec[]>();
  for (const s of specs) {
    const arr = bySection.get(s.section) ?? [];
    arr.push(s);
    bySection.set(s.section, arr);
  }

  const picked: AssetSpec[] = [];
  // Round-robin one from each section first.
  const sections = [...bySection.keys()];
  let round = 0;
  while (picked.length < limit) {
    let pickedThisRound = 0;
    for (const section of sections) {
      if (picked.length >= limit) break;
      const bucket = bySection.get(section)!;
      if (round < bucket.length) {
        picked.push(bucket[round]);
        pickedThisRound++;
      }
    }
    if (pickedThisRound === 0) break;
    round++;
  }
  return picked;
}

function buildRecord(args: {
  spec: AssetSpec;
  packTitle: string | undefined;
  preset: string;
  fmt: { prompt: FormattedImagePrompt; cost_usd: number };
  model: string;
  taskId: string;
  imageCostUsd: number;
  durationMs: number;
}): GenerationRecord {
  return {
    pack_title: args.packTitle,
    preset: args.preset,
    spec_id: args.spec.id,
    file: args.spec.file,
    spec_type: args.spec.type,
    section_id: args.spec.section_id,
    section: args.spec.section,
    style_id: args.spec.style_id,
    palette_id: args.spec.palette_id,
    identity_id: args.spec.identity_id,
    model: args.model,
    size: args.spec.size,
    aspect: args.spec.aspect,
    prompt_fragment: args.spec.prompt_fragment,
    raw_description: args.spec.description,
    formatted_prompt: args.fmt.prompt,
    bfl_task_id: args.taskId,
    cost_usd: args.imageCostUsd,
    claude_cost_usd: args.fmt.cost_usd,
    duration_ms: args.durationMs,
    generated_at: new Date().toISOString(),
  };
}

function buildPreviewOutput(
  spec: AssetSpec,
  prompt: FormattedImagePrompt,
): string {
  const rendered =
    typeof prompt === "string" ? prompt : JSON.stringify(prompt, null, 2);
  return `\n--- ${spec.id} (${spec.file}) ---\n${rendered}`;
}

function getFormatterForSpec(
  spec: AssetSpec,
  styles: Record<string, import("./types.js").StyleAnchor>,
  palettes: Record<string, import("./types.js").Palette>,
  cache: Map<string, ClaudeFormatter>,
  apiKey: string,
  imageModel: string,
): ClaudeFormatter {
  const key = `${imageModel}\u0000${spec.style_id}\u0000${spec.palette_id}`;
  let formatter = cache.get(key);
  if (!formatter) {
    formatter = new ClaudeFormatter({
      apiKey,
      style: styles[spec.style_id],
      palette: palettes[spec.palette_id],
      imageModel,
    });
    cache.set(key, formatter);
  }
  return formatter;
}

interface ImageClient {
  generate(request: {
    prompt: FormattedImagePrompt;
    size?: string;
    aspect?: string;
  }): Promise<{
    image: Buffer;
    task_id: string;
    cost_usd: number;
    duration_ms: number;
    model: string;
    size: string;
  }>;
}

function createImageClient(args: {
  model: string;
  bflApiKey: string;
  openaiApiKey: string;
}): ImageClient {
  const provider = getImageProvider(args.model);
  if (provider === "bfl") {
    if (!args.bflApiKey) {
      throw new Error("BFL_API_KEY is required for BFL image models.");
    }
    return new BflClient({
      apiKey: args.bflApiKey,
      model: args.model,
    });
  }

  if (!args.openaiApiKey) {
    throw new Error("OPENAI_API_KEY is required for OpenAI image models.");
  }
  return new OpenAiImageClient({
    apiKey: args.openaiApiKey,
    model: args.model,
  });
}
